### ISSUE TITLE
What if there are no subfolders test/train? 

### ISSUE THREAD

**Issue by ahinoampollack** [Spenhouet/tensorboard-aggregator#2]
**Describe the bug**
if there are no subfolders then the code doesn't work. 
Get an error: 
/path/test is not a valid path --> since there is no test folder.

**Comment by Spenhouet** [comment]
Hi @ahinoampollack,

please try the parameter `subpaths` with the argument `"['.']"` (with or without outer quotes, not sure if os dependent). 

`python aggregator.py --subpaths "['.']"`

Does that work?

**Comment by ahinoampollack** [comment]
Yes! it does.

Thank you so much for your time!

I now have a new error though (do you want me to start a new thread?): 

> For scalar val_loss the step numbering or count doesn't match. Step count for all runs: [600, 100, 187, 300, 300, 500, 400, 100, 400, 284, 600, 500, 300, 100, 500, 200, 200, 200, 200, 600, 400, 200, 600, 400, 400,

since not all of my runs have the same number of steps

**Comment by Spenhouet** [comment]
Sorry to hear that but this is a limitation of the implementation.

https://github.com/Spenhouet/tensorboard-aggregator#limitations

It is only possible to aggregate runs that have the same number of steps.

**Comment by ahinoampollack** [comment]
Ok! thanks. 
I'll use this as a starting code!

**Comment by Spenhouet** [comment]
I hope you get it to work 👍 

If you do and the current functionality still works you could consider a pull request :)

EDIT: I forgot that this issue was raised in the past. There are reasons to not support it in this project.
For the reasons take a look here: https://github.com/Spenhouet/tensorboard-aggregator/issues/1#issuecomment-461904929
